# Generated by Django 4.0.2 on 2022-03-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0005_alter_apointment_a_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apointment',
            name='a_service',
            field=models.ManyToManyField(related_name='apoint_service', to='one.services'),
        ),
    ]
