# Generated by Django 4.0.2 on 2022-03-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0007_alter_apointment_a_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='apointment',
            new_name='appointments',
        ),
    ]
