# Generated by Django 4.0.2 on 2022-03-27 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0010_alter_apointment_a_client_alter_apointment_a_salon_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apointment',
            unique_together=set(),
        ),
    ]
