# Generated by Django 4.0.2 on 2022-05-14 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0011_alter_apointment_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_total_price', models.FloatField(null=True)),
                ('a_total_etime', models.IntegerField(null=True)),
                ('c_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='one.client')),
                ('c_salon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='one.salon')),
                ('c_service', models.ManyToManyField(related_name='cart_service', to='one.services')),
            ],
        ),
    ]
