# Generated by Django 4.0.2 on 2022-05-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0012_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apointment',
            name='a_total_etime',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
