# Generated by Django 4.0.2 on 2022-05-14 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0014_alter_cart_a_total_etime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='a_total_etime',
            new_name='c_total_etime',
        ),
    ]
