# Generated by Django 4.0.2 on 2022-05-14 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0016_remove_apointment_a_total_etime_apointment_a_ehour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='c_total_etime',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='c_total_price',
        ),
    ]
